---
title: "Leaflet"
author: "Vijay"
date: "May 26, 2017"
output: html_document
---

##Objective##
This document covers all major cities in India and also gives the information about each city when you click on the marker.

```{r , echo= TRUE}
library(leaflet)
```

Using leaflet package, creating a map and mark all major cities in India. Click on the marker to explore more about city

```{r}
city <-  c("Hyderabad","Pune","New Delhi","Mumbai","Kolkata", "Chennai")
lat <- c(17.3850,18.5204,28.6139,19.0760,22.5726, 13.0827)
lng <- c(78.4867,73.8567,77.2090,72.8777,88.3639, 80.2707)
df <- data.frame(lat, lng)
cityurl <- c(
        "<a href = 'https://en.wikipedia.org/wiki/Hyderabad'>HYDERABAD</a>",
        "<a href = 'https://en.wikipedia.org/wiki/Pune'>Pune</a>",
        "<a href = 'https://en.wikipedia.org/wiki/New_Delhi'>New Delhi</a>",
        "<a href = 'https://en.wikipedia.org/wiki/Mumbai'>Mumbai</a>",
        "<a href = 'https://en.wikipedia.org/wiki/Kolkata'>Kolkata</a>",
        "<a href = 'https://en.wikipedia.org/wiki/Chennai'>Chennai</a>"
)
df %>% leaflet() %>% addTiles() %>% addMarkers(popup = cityurl)
```

